import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        {/* nav bar  */}
        <nav className="nav-bar">
          <div className="logo">Md Mohsin haider</div>
          <ul className="nav-links">
            <li>
              <a href="#">Home</a>
            </li>
            <li>
              <a href="#">About</a>
            </li>
            <li>
              <a href="#">Services</a>
            </li>
            <li>
              <a href="#">Profile</a>
            </li>
          </ul>
          <div className="user-profile">
            <div className="dropdown">
              <button className="dropbtn">Profile</button>
              <div className="dropdown-content">
                <a href="#">Settings</a>
                <a href="#">Your Profile</a>
              </div>
            </div>
          </div>
        </nav>
        <hr />
        {children}
      </body>
    </html>
  );
}
